<#
  Builds a personalised, double-clickable installer for a second machine.

  setup-relay.cmd already automates the install, but it stops three times to
  ask for the Worker URL, the ingest token and the plant ids - which means
  carrying those values to the other machine and typing them correctly. This
  reads them out of the .dev.vars here and bakes them into a single .cmd file
  you copy across and double-click.

  The generated file CONTAINS YOUR INGEST TOKEN in plain text. That token only
  permits pushing readings - it cannot read your dashboard and cannot reach
  your Cloudflare account - but treat the file as a key all the same: carry it
  on a USB stick rather than emailing it, and delete it from both machines
  afterwards. It is written outside the repository on purpose.

  One step still needs a person at the other end: signing in to SolisCloud.
  The whole point of the relay is that it drives a logged-in browser session,
  and no script can type a password into a login form on your behalf.

  Usage:
    .\scripts\make-laptop-installer.ps1
    .\scripts\make-laptop-installer.ps1 -OutFile D:\usb\setup-solarlens.cmd
#>
[CmdletBinding()]
param(
  [string] $OutFile
)

$ErrorActionPreference = 'Stop'

function Ok($t)   { Write-Host "    OK  $t" -ForegroundColor Green }
function Warn($t) { Write-Host "    !!  $t" -ForegroundColor Yellow }
function Die($t)  { Write-Host "    XX  $t" -ForegroundColor Red; exit 1 }

$root    = Split-Path $PSScriptRoot -Parent
$devVars = Join-Path $root '.dev.vars'
if (-not (Test-Path $devVars)) { Die "No .dev.vars at $devVars - run this on the machine that already works." }

$vars = @{}
Get-Content $devVars | ForEach-Object {
  if ($_ -match '^\s*([A-Z0-9_]+)\s*=\s*(.*)$') { $vars[$matches[1]] = $matches[2].Trim() }
}

$url    = $vars['SOLARLENS_URL']
$token  = $vars['INGEST_TOKEN']
$plants = $vars['SOLIS_PLANT_IDS']

if (-not $url)   { Die 'SOLARLENS_URL is not set in .dev.vars.' }
if (-not $token) { Die 'INGEST_TOKEN is not set in .dev.vars.' }
if ($token -eq 'RECOVER-ME' -or $url -eq 'RECOVER-ME') {
  Die 'INGEST_TOKEN still reads RECOVER-ME. Run scripts\rotate-tokens.ps1 -Ingest first.'
}

# A stray quote or percent sign in a value would break the batch file it is
# pasted into. These are generated tokens and ids, so it should never happen -
# but "should never" is how broken installers get shipped.
foreach ($pair in @(@('SOLARLENS_URL', $url), @('INGEST_TOKEN', $token), @('SOLIS_PLANT_IDS', $plants))) {
  if ($pair[1] -match "['`"%&|<>^]") { Die "$($pair[0]) contains a character that cannot be embedded safely. Set it on the other machine by hand instead." }
}

if (-not $OutFile) {
  $OutFile = Join-Path ([Environment]::GetFolderPath('Desktop')) 'setup-solarlens-relay.cmd'
}

$plantArg = if ($plants) { " -PlantIds '$plants'" } else { '' }
$raw = 'https://raw.githubusercontent.com/muhammadmobi/SolarLens/main/scripts/setup-relay.ps1'

# Written as one PowerShell -Command line so the file stays a plain .cmd that
# Windows will run on a double-click. Values are in single quotes: PowerShell
# does not expand anything inside those, so a token cannot be mangled.
$body = @"
@echo off
REM ---------------------------------------------------------------------
REM  SolarLens relay - one-click setup for a second machine.
REM
REM  Generated by scripts\make-laptop-installer.ps1. This file contains an
REM  ingest token: treat it as a key, and delete it once the setup is done.
REM
REM  It installs whatever is missing (Node, Git, Chrome), fetches the code,
REM  and registers the relay to start at every logon. The only thing it will
REM  ask you for is your SolisCloud login, in the browser window it opens.
REM ---------------------------------------------------------------------

echo.
echo  Setting up the SolarLens relay on this machine.
echo  Nothing to type until a Chrome window opens on the SolisCloud login.
echo.

powershell -NoProfile -ExecutionPolicy Bypass -Command "`$ErrorActionPreference='Stop'; `$f=Join-Path `$env:TEMP 'solarlens-setup-relay.ps1'; `$got=`$false; foreach (`$i in 1..5) { try { Invoke-WebRequest '$raw' -OutFile `$f -UseBasicParsing -TimeoutSec 30; `$got=`$true; break } catch { Write-Host ('  download attempt ' + `$i + ' failed, retrying...') -ForegroundColor DarkGray; Start-Sleep -Seconds 4 } }; if (-not `$got) { Write-Host 'Could not download the setup script. GitHub may be busy - wait a minute and run this file again.' -ForegroundColor Red; exit 1 }; & `$f -WorkerUrl '$url' -IngestToken '$token'$plantArg"

echo.
echo  Finished. You can delete this file now.
echo.
pause
"@

Set-Content -Path $OutFile -Value $body -Encoding ascii
Ok "Written to $OutFile"

Write-Host ''
Write-Host '  Copy that file to the other laptop and double-click it.' -ForegroundColor Cyan
Write-Host '  It will ask you for nothing except the SolisCloud login in the browser.'
Write-Host ''
Warn 'It contains your ingest token. Carry it on a USB stick, not by email, and delete it afterwards.'
